version: '3.8'

services:
  myproject:
    image: myproject_image:latest
    build: .
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
      restart_policy:
        condition: on-failure